[profile.default]
src = "contracts/src"
script = "contracts/script"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
]
